# Generated by Django 5.2.4 on 2025-08-12 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0003_alter_player_contract_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='current_balance',
        ),
        migrations.AddField(
            model_name='gameweek',
            name='season',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='gameweeks', to='TeamManage.seasonconfig'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seasonconfig',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='gameweek',
            unique_together={('season', 'number')},
        ),
    ]
