# Generated by Django 5.2.4 on 2025-08-12 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0004_remove_team_current_balance_gameweek_season_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonconfig',
            name='start_balance',
        ),
        migrations.AddField(
            model_name='team',
            name='current_balance',
            field=models.FloatField(blank=True, help_text='Running balance updated weekly', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='start_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transferhistory',
            name='is_loan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transferhistory',
            name='loan_duration_gw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferhistory',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamManage.seasonconfig'),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
