# Generated by Django 5.2.4 on 2025-08-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0005_remove_seasonconfig_start_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonconfig',
            name='active',
        ),
        migrations.RemoveField(
            model_name='team',
            name='start_balance',
        ),
        migrations.AddField(
            model_name='seasonconfig',
            name='current_gameweek',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='GameWeek',
        ),
    ]
