# Generated by Django 5.2.4 on 2025-08-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0006_remove_seasonconfig_active_remove_team_start_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonconfig',
            name='is_season_active',
            field=models.BooleanField(default=False),
        ),
    ]
