# Generated by Django 5.2.4 on 2025-08-12 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0008_matchround_match_delete_transferhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['round']},
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='TeamManage.seasonconfig')),
            ],
            options={
                'ordering': ['season', 'round_number'],
                'unique_together': {('season', 'round_number')},
            },
        ),
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='TeamManage.round'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('round', 'home_team', 'away_team')},
        ),
        migrations.DeleteModel(
            name='MatchRound',
        ),
    ]
