# Generated by Django 5.2.4 on 2025-08-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0009_alter_match_options_round_alter_match_round_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['round_number']},
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('round_number',)},
        ),
        migrations.AlterField(
            model_name='round',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='round',
            name='season',
        ),
    ]
