# Generated by Django 5.2.4 on 2025-08-12 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0010_alter_round_options_alter_round_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['season', 'round_number']},
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='round',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='TeamManage.seasonconfig'),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('season', 'round_number')},
        ),
    ]
