# Generated by Django 5.2.4 on 2025-08-13 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0011_alter_round_options_alter_round_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='club_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='TeamManage.seasonconfig'),
        ),
    ]
