# Generated by Django 5.2.4 on 2025-08-13 20:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0012_player_club_name_alter_round_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('is_loan', models.BooleanField(default=False)),
                ('loan_gameweek', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('returned_from_loan', models.BooleanField(default=False)),
                ('from_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='TeamManage.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamManage.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamManage.seasonconfig')),
                ('to_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='TeamManage.team')),
            ],
        ),
    ]
