# Generated by Django 5.2.4 on 2025-08-13 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0013_transferhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferhistory',
            name='returned_from_loan',
        ),
        migrations.AddField(
            model_name='player',
            name='is_loan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='from_team',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='TeamManage.team'),
        ),
    ]
