# Generated by Django 5.2.4 on 2025-08-13 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0014_remove_transferhistory_returned_from_loan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerForTransfer',
            fields=[
            ],
            options={
                'verbose_name': 'Player for Transfer',
                'verbose_name_plural': 'Players for Transfer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TeamManage.player',),
        ),
    ]
