# Generated by Django 5.2.4 on 2025-08-13 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0015_playerfortransfer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerForTransfer',
        ),
    ]
