# Generated by Django 5.2.4 on 2025-08-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0018_player_loan_from_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferhistory',
            name='is_loan_end',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
