# Generated by Django 5.2.4 on 2025-08-19 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0019_transferhistory_is_loan_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bonus_earning',
            field=models.FloatField(default=0, help_text='Total bonus earned by the player'),
        ),
        migrations.CreateModel(
            name='WeeklyBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameweek', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('highest_df_players', models.ManyToManyField(blank=True, related_name='highest_df_bonus', to='TeamManage.player')),
                ('highest_fw_players', models.ManyToManyField(blank=True, related_name='highest_fw_bonus', to='TeamManage.player')),
                ('highest_gk_players', models.ManyToManyField(blank=True, related_name='highest_gk_bonus', to='TeamManage.player')),
                ('highest_mf_players', models.ManyToManyField(blank=True, related_name='highest_mf_bonus', to='TeamManage.player')),
                ('highest_point_players', models.ManyToManyField(blank=True, related_name='highest_point_bonus', to='TeamManage.player')),
                ('highest_point_teams', models.ManyToManyField(blank=True, related_name='highest_point_bonus', to='TeamManage.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamManage.seasonconfig')),
                ('team_of_the_week_players', models.ManyToManyField(blank=True, related_name='team_of_week_bonus', to='TeamManage.player')),
            ],
        ),
    ]
