# Generated by Django 5.2.4 on 2025-08-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0020_player_bonus_earning_weeklybonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bonus_income',
            field=models.FloatField(default=0, help_text='Total bonus income earned by the team'),
        ),
    ]
