# Generated by Django 5.2.4 on 2025-08-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0021_team_bonus_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklybonus',
            name='bonuses_applied',
            field=models.BooleanField(default=False, help_text='Track if bonuses have been applied'),
        ),
    ]
