# Generated by Django 5.2.4 on 2025-08-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0022_weeklybonus_bonuses_applied'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklybonus',
            unique_together={('season', 'gameweek')},
        ),
        migrations.AddField(
            model_name='weeklybonus',
            name='additional_players',
            field=models.ManyToManyField(blank=True, related_name='bonus_additional', to='TeamManage.player'),
        ),
        migrations.AddField(
            model_name='weeklybonus',
            name='highest_def_players',
            field=models.ManyToManyField(blank=True, related_name='bonus_highest_def', to='TeamManage.player'),
        ),
        migrations.AddField(
            model_name='weeklybonus',
            name='highest_fwd_players',
            field=models.ManyToManyField(blank=True, related_name='bonus_highest_fwd', to='TeamManage.player'),
        ),
        migrations.AddField(
            model_name='weeklybonus',
            name='highest_mid_players',
            field=models.ManyToManyField(blank=True, related_name='bonus_highest_mid', to='TeamManage.player'),
        ),
        migrations.AlterField(
            model_name='weeklybonus',
            name='gameweek',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='weeklybonus',
            name='highest_gk_players',
            field=models.ManyToManyField(blank=True, related_name='bonus_highest_gk', to='TeamManage.player'),
        ),
        migrations.AlterField(
            model_name='weeklybonus',
            name='highest_point_players',
            field=models.ManyToManyField(blank=True, related_name='bonus_highest_point', to='TeamManage.player'),
        ),
        migrations.AlterField(
            model_name='weeklybonus',
            name='highest_point_teams',
            field=models.ManyToManyField(blank=True, related_name='bonus_highest_point', to='TeamManage.team'),
        ),
        migrations.RemoveField(
            model_name='weeklybonus',
            name='bonuses_applied',
        ),
        migrations.RemoveField(
            model_name='weeklybonus',
            name='highest_df_players',
        ),
        migrations.RemoveField(
            model_name='weeklybonus',
            name='highest_fw_players',
        ),
        migrations.RemoveField(
            model_name='weeklybonus',
            name='highest_mf_players',
        ),
        migrations.RemoveField(
            model_name='weeklybonus',
            name='team_of_the_week_players',
        ),
    ]
