# Generated by Django 5.2.4 on 2025-08-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0023_alter_weeklybonus_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklybonus',
            name='bonuses_applied',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
