# Generated by Django 5.2.4 on 2025-08-20 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0024_weeklybonus_bonuses_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklybonus',
            name='bonuses_applied',
        ),
        migrations.AlterField(
            model_name='weeklybonus',
            name='season',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='TeamManage.seasonconfig'),
        ),
    ]
