# Generated by Django 5.2.4 on 2025-08-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0025_remove_weeklybonus_bonuses_applied_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklybonus',
            options={'ordering': ['-season', '-gameweek']},
        ),
        migrations.RemoveField(
            model_name='weeklybonus',
            name='additional_players',
        ),
        migrations.RemoveField(
            model_name='weeklybonus',
            name='highest_def_players',
        ),
        migrations.RemoveField(
            model_name='weeklybonus',
            name='highest_fwd_players',
        ),
        migrations.RemoveField(
            model_name='weeklybonus',
            name='highest_mid_players',
        ),
        migrations.AddField(
            model_name='weeklybonus',
            name='highest_df_players',
            field=models.ManyToManyField(blank=True, related_name='bonus_highest_df', to='TeamManage.player'),
        ),
        migrations.AddField(
            model_name='weeklybonus',
            name='highest_fw_players',
            field=models.ManyToManyField(blank=True, related_name='bonus_highest_fw', to='TeamManage.player'),
        ),
        migrations.AddField(
            model_name='weeklybonus',
            name='highest_mf_players',
            field=models.ManyToManyField(blank=True, related_name='bonus_highest_mf', to='TeamManage.player'),
        ),
        migrations.AddField(
            model_name='weeklybonus',
            name='special_bonus_players',
            field=models.ManyToManyField(blank=True, related_name='bonus_special', to='TeamManage.player'),
        ),
    ]
