# Generated by Django 5.2.4 on 2025-08-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0026_alter_weeklybonus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year', 'season'],
                'constraints': [models.UniqueConstraint(fields=('season', 'year'), name='unique_transfer_window')],
            },
        ),
    ]
