# Generated by Django 5.2.4 on 2025-08-27 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0027_transferwindow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='TeamManage.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='TeamManage.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
