# Generated by Django 5.2.4 on 2025-08-28 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0028_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='TeamManage.player'),
        ),
    ]
