# Generated by Django 5.2.4 on 2025-09-08 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0032_alter_newspost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='total_draws',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='total_losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='total_wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='win_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='TeamSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('win_percentage', models.FloatField(default=0.0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamManage.seasonconfig')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='TeamManage.team')),
            ],
            options={
                'unique_together': {('team', 'season')},
            },
        ),
    ]
