# Generated by Django 5.2.4 on 2025-09-08 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0034_alter_newspost_author_alter_player_contract_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contract_expiry',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format must be like: Summer 2026 or Winter 2028', regex='^(Summer|Winter) \\d{4}$')]),
        ),
    ]
