# Generated by Django 5.2.4 on 2025-09-08 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0035_alter_player_contract_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contract_expiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players_with_contract_expiry', to='TeamManage.transferwindow'),
        ),
    ]
