# Generated by Django 5.2.4 on 2025-09-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0036_alter_player_contract_expiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferwindow',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='player',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
