# Generated by Django 5.2.4 on 2025-09-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0037_alter_transferwindow_options_player_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='nationality',
        ),
    ]
