# Generated by Django 5.2.4 on 2025-09-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0038_remove_player_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='was_academy_player',
            field=models.BooleanField(default=False),
        ),
    ]
