# Generated by Django 5.2.4 on 2025-09-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0039_player_was_academy_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='base_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='bonus_earning',
            field=models.DecimalField(decimal_places=5, default=0, help_text='Total bonus earned by the player', max_digits=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='contract_renew_bonus',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='bonus_income',
            field=models.DecimalField(decimal_places=5, default=0, help_text='Total bonus income earned by the team', max_digits=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Running balance updated weekly', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='amount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
