# Generated by Django 5.2.4 on 2025-09-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0040_alter_bid_amount_alter_player_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
