# Generated by Django 5.2.4 on 2025-09-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0041_alter_bid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferwindow',
            name='is_contract_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
