# Generated by Django 5.2.4 on 2025-09-12 22:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0042_transferwindow_is_contract_open_alter_bid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferhistory',
            name='transfer_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
