# Generated by Django 5.2.4 on 2025-09-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0044_round_is_ended_alter_match_away_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='is_ended',
        ),
    ]
