# Generated by Django 5.2.4 on 2025-09-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0045_remove_round_is_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
    ]
