# Generated by Django 5.2.4 on 2025-09-16 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0046_round_is_ended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamseasonstats',
            name='win_percentage',
        ),
        migrations.AlterField(
            model_name='teamseasonstats',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='TeamManage.seasonconfig'),
        ),
    ]
