# Generated by Django 5.2.4 on 2025-09-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0048_transferrequest_transferrequestitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferrequestitem',
            name='transfer_request',
        ),
        migrations.RemoveField(
            model_name='transferrequestitem',
            name='player',
        ),
        migrations.DeleteModel(
            name='TransferRequest',
        ),
        migrations.DeleteModel(
            name='TransferRequestItem',
        ),
    ]
