# Generated by Django 5.2.4 on 2025-09-20 07:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0049_remove_transferrequestitem_transfer_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=10)),
                ('is_loan', models.BooleanField(default=False)),
                ('loan_gameweek', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_made', to=settings.AUTH_USER_MODEL)),
                ('from_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_received', to='TeamManage.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='TeamManage.player')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamManage.seasonconfig')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_sent', to='TeamManage.team')),
            ],
        ),
    ]
