# Generated by Django 5.2.4 on 2025-09-21 18:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0050_transferrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrequest',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=10),
        ),
    ]
