# Generated by Django 5.2.4 on 2025-09-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0051_alter_transferrequest_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='total_draws',
        ),
        migrations.RemoveField(
            model_name='team',
            name='total_losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='total_wins',
        ),
        migrations.RemoveField(
            model_name='team',
            name='win_percentage',
        ),
    ]
