# Generated by Django 5.2.4 on 2025-09-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0052_remove_team_total_draws_remove_team_total_losses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='was_locked',
            field=models.BooleanField(default=False),
        ),
    ]
