# Generated by Django 5.2.4 on 2025-09-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0053_player_was_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_transfer_lock',
            field=models.BooleanField(default=False),
        ),
    ]
