# Generated by Django 5.2.4 on 2025-09-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0054_player_is_transfer_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contract_renew_bonus',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
