# Generated by Django 5.2.4 on 2025-09-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0055_alter_player_contract_renew_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferhistory',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
