# Generated by Django 5.2.4 on 2025-09-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0056_alter_transferhistory_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bonus_earning',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Total bonus earned by the player', max_digits=10),
        ),
    ]
