# Generated by Django 5.2.4 on 2025-09-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0058_remove_newspost_image_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
