# Generated by Django 5.2.4 on 2025-09-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0059_newspost_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspost',
            old_name='image',
            new_name='title_image',
        ),
    ]
