# Generated by Django 5.2.4 on 2025-09-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0060_rename_image_newspost_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
