# Generated by Django 5.2.4 on 2025-09-30 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0061_bid_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferhistory',
            name='from_team',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='TeamManage.team'),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='to_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='TeamManage.team'),
        ),
    ]
