# Generated by Django 5.2.4 on 2025-10-01 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0062_alter_transferhistory_from_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_champion', models.CharField(blank=True, max_length=500, null=True)),
                ('league_runner_up', models.CharField(blank=True, max_length=500, null=True)),
                ('ucl_champion', models.CharField(blank=True, max_length=500, null=True)),
                ('ucl_runner_up', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='TeamManage.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamAchievementRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='TeamManage.teamachievement')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_ranks', to='TeamManage.seasonconfig')),
            ],
            options={
                'unique_together': {('achievement', 'season')},
            },
        ),
    ]
