# Generated by Django 5.2.4 on 2025-10-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0063_teamachievement_teamachievementrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
