# Generated by Django 5.2.4 on 2025-10-02 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0065_alter_player_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferhistory',
            name='season',
        ),
        migrations.AddField(
            model_name='transferhistory',
            name='window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='TeamManage.transferwindow'),
        ),
    ]
