# Generated by Django 5.2.4 on 2025-10-02 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0066_remove_transferhistory_season_transferhistory_window'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferhistory',
            name='window',
        ),
        migrations.AddField(
            model_name='transferhistory',
            name='season',
            field=models.ForeignKey(default=77.88461538461539, on_delete=django.db.models.deletion.CASCADE, to='TeamManage.seasonconfig'),
            preserve_default=False,
        ),
    ]
