# Generated by Django 5.2.4 on 2025-10-02 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0067_remove_transferhistory_window_transferhistory_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferwindow',
            name='free_transfer_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
