# Generated by Django 5.2.4 on 2025-10-04 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0069_maintenancemode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_loan_gameweek', models.IntegerField()),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_extension_requests', to='TeamManage.team')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_extensions', to='TeamManage.transferhistory')),
            ],
        ),
    ]
