# Generated by Django 5.2.4 on 2025-10-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0070_loanextensionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default='default_human.png', null=True, upload_to='player_photos/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to='team_logos/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager_photo',
            field=models.ImageField(blank=True, default='default_human.png', null=True, upload_to='manager_photos/'),
        ),
    ]
