# Generated by Django 5.2.4 on 2025-10-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0071_alter_player_photo_alter_team_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='base_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='bonus_earning',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Total bonus earned by the player', max_digits=4),
        ),
        migrations.AlterField(
            model_name='team',
            name='bonus_income',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Total bonus income earned by the team', max_digits=6),
        ),
        migrations.AlterField(
            model_name='team',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Running balance updated weekly', max_digits=12, null=True),
        ),
    ]
