# Generated by Django 5.2.4 on 2025-10-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0072_alter_player_base_price_alter_player_bonus_earning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklybonus',
            name='is_bonus_applied',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
