# Generated by Django 5.2.4 on 2025-10-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0073_weeklybonus_is_bonus_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklybonus',
            name='is_bonus_applied',
        ),
    ]
