# Generated by Django 5.2.4 on 2025-10-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0074_remove_weeklybonus_is_bonus_applied'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
