# Generated by Django 5.2.4 on 2025-10-15 16:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0075_delete_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
