# Generated by Django 5.2.4 on 2025-10-15 21:32

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0076_alter_newspost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
