# Generated by Django 5.2.4 on 2025-11-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0077_alter_newspost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default='human.png', null=True, upload_to='player_photos/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager_photo',
            field=models.ImageField(blank=True, default='human.png', null=True, upload_to='manager_photos/'),
        ),
    ]
