# Generated by Django 5.2.4 on 2025-11-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0078_alter_player_photo_alter_team_manager_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonstats',
            name='goals_against',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='goals_for',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
