# Generated by Django 5.2.4 on 2025-11-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0079_teamseasonstats_goals_against_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamseasonstats',
            name='goals_against',
        ),
        migrations.RemoveField(
            model_name='teamseasonstats',
            name='goals_for',
        ),
    ]
