# Generated by Django 5.2.4 on 2025-11-04 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0080_remove_teamseasonstats_goals_against_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSeasonRanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('goals_for', models.PositiveIntegerField(default=0)),
                ('goals_against', models.PositiveIntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_ranks', to='TeamManage.seasonconfig')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_ranks', to='TeamManage.team')),
            ],
            options={
                'unique_together': {('team', 'season')},
            },
        ),
    ]
