# Generated by Django 5.2.4 on 2025-11-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0081_teamseasonranks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamachievementrank',
            old_name='rank',
            new_name='league_rank',
        ),
        migrations.AddField(
            model_name='teamachievementrank',
            name='ucl_rank',
            field=models.IntegerField(default=77.88461538461539),
            preserve_default=False,
        ),
    ]
