# Generated by Django 5.2.4 on 2025-11-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0082_rename_rank_teamachievementrank_league_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamachievementrank',
            name='ucl_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
