# Generated by Django 5.2.4 on 2025-11-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0083_alter_teamachievementrank_ucl_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamachievement',
            name='blon_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='blon_winning_season',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
