# Generated by Django 5.2.4 on 2025-11-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0084_teamachievement_blon_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamachievement',
            old_name='blon_amount',
            new_name='blon_count',
        ),
    ]
