# Generated by Django 5.2.4 on 2025-11-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0086_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='bg_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
