# Generated by Django 5.2.4 on 2025-11-06 12:56

import TeamManage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0087_story_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=TeamManage.models.story_media_path),
        ),
    ]
