# Generated by Django 5.2.4 on 2025-11-08 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0088_story_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('HOME', 'Home Win'), ('AWAY', 'Away Win'), ('DRAW', 'Draw')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='TeamManage.match')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='TeamManage.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'round', 'match')},
            },
        ),
    ]
