# Generated by Django 5.2.4 on 2025-11-09 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0089_matchprediction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchprediction',
            name='created_at',
        ),
        migrations.AddField(
            model_name='matchprediction',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchprediction',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchprediction',
            name='rewarded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='team',
            name='prediction_bonus_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='matchprediction',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamManage.match'),
        ),
        migrations.AlterField(
            model_name='matchprediction',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamManage.round'),
        ),
        migrations.AlterField(
            model_name='matchprediction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
