# Generated by Django 5.2.4 on 2025-11-09 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0090_remove_matchprediction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchprediction',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='TeamManage.match'),
        ),
    ]
