# Generated by Django 5.2.4 on 2025-11-11 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0091_alter_matchprediction_match'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamSeasonStats',
        ),
    ]
