# Generated by Django 5.2.4 on 2025-11-15 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0092_delete_teamseasonstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3)),
                ('bonus_amount', models.DecimalField(decimal_places=1, max_digits=6)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamManage.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamManage.seasonconfig')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamManage.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('season', 'month', 'team', 'player'), name='unique_monthly_bonus_record')],
            },
        ),
    ]
