# Generated by Django 5.2.4 on 2025-11-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0093_monthlybonus'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='monthlybonus',
            name='unique_monthly_bonus_record',
        ),
        migrations.AddField(
            model_name='monthlybonus',
            name='category',
            field=models.CharField(choices=[('POM', 'Player of the Month'), ('GOM', 'Goal of the Month'), ('SOM', 'Save of the Month')], default='POM', max_length=3),
        ),
        migrations.AlterField(
            model_name='monthlybonus',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=1, editable=False, max_digits=6),
        ),
        migrations.AddConstraint(
            model_name='monthlybonus',
            constraint=models.UniqueConstraint(fields=('season', 'month', 'team', 'player', 'category'), name='unique_monthly_bonus_record'),
        ),
    ]
