# Generated by Django 5.2.4 on 2025-11-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0094_remove_monthlybonus_unique_monthly_bonus_record_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='monthlybonus',
            name='unique_monthly_bonus_record',
        ),
        migrations.AddConstraint(
            model_name='monthlybonus',
            constraint=models.UniqueConstraint(fields=('season', 'month', 'category'), name='unique_monthly_bonus_record'),
        ),
    ]
