# Generated by Django 5.2.4 on 2025-11-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0095_remove_monthlybonus_unique_monthly_bonus_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybonus',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
