# Generated by Django 5.2.4 on 2025-11-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0096_monthlybonus_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybonus',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
