# Generated by Django 5.2.4 on 2025-11-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0097_alter_monthlybonus_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlybonus',
            name='date',
        ),
    ]
