# Generated by Django 5.2.4 on 2025-11-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0098_remove_monthlybonus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanextensionrequest',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
