# Generated by Django 5.2.4 on 2025-11-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0099_loanextensionrequest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferhistory',
            name='back_from_loan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transferhistory',
            name='to_loan',
            field=models.BooleanField(default=False),
        ),
    ]
