# Generated by Django 5.2.4 on 2025-11-17 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0100_transferhistory_back_from_loan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybonus',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamManage.team'),
        ),
    ]
